feat: get the action and the tests working (#4)
* create a test to run manually or when there is a PR and a change
* Use gh pr ready cli command to convert
* Create CODEOWNERS
* remove PR after test
* add not to test about needing to delete an existing PR used for testing

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -15,17 +15,18 @@ jobs:
     steps:
       - name: checkout
         uses: actions/checkout@v3.0.2
+        with:
+          ref: ${{ github.head_ref }}
 
       - name: Create commits
         run: |
+          set -o xtrace
           git config user.name 'leemeador'
           git config user.email 'lee@leemeador.com'
           test -d ./testfiles || mkdir ./testfiles
           date +%s > testfiles/report.txt
-          git commit -am "Modify tracked file during workflow"
-          date +%s > testfiles/new-report.txt
-          git add -A
-          git commit -m "Add untracked file during workflow"
+          git add testfiles/report.txt
+          git commit -m "Modify tracked file during workflow"
 
       - name: Create Pull Request
         id: create-pr
@@ -33,21 +34,47 @@ jobs:
         with:
           draft: true
  
+      # If PR already exists from a failed test and PR is not in dreaft, it will not be changed to draft
       - name: Check outputs
-        if: ${{ steps.cpr.outputs.pull-request-number }}
+        if: ${{ steps.create-pr.outputs.pull-request-number }}
         run: |
-          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
-          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"      
+          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
+          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"      
+
+      - name: verify the PR is in draft
+        env:
+           GH_TOKEN: ${{ secrets.GIT_TOKEN }}
+        shell: bash
+        run: |
+          set -o xtrace
+          export IS_DRAFT="$(gh pr view ${{ steps.create-pr.outputs.pull-request-number }} --json isDraft  --jq .isDraft)"
+          echo "isDraft: ${IS_DRAFT}"
+          if [ "${IS_DRAFT}" = "false" ]; then
+              echo "ERROR: PR already exists as ready-to-review. Please delete the PR and rerun this test."
+              exit 1
+          fi
 
       - name: Mark as Ready to release
         uses: ./
         with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          pr-number: ${{ steps.cpr.outputs.pull-request-number }}
+          token: ${{ secrets.GIT_TOKEN }}
+          pr-number: ${{ steps.create-pr.outputs.pull-request-number }}
 
       - name: verify the action
+        env:
+           GH_TOKEN: ${{ secrets.GIT_TOKEN }}
+        shell: bash
         run: |
-          IS_DRAFT=$(gh pr view 13 --json isDraft  --jq .isDraft)
-          if [ "$IS_DRAFT" = "true" ]; then
+          set -o xtrace
+          export IS_DRAFT="$(gh pr view ${{ steps.create-pr.outputs.pull-request-number }} --json isDraft  --jq .isDraft)"
+          echo "isDraft: ${IS_DRAFT}"
+          if [ "${IS_DRAFT}" = "true" ]; then
               exit 1
           fi
+
+      - name: Close and delete PR used for testing
+        uses: peter-evans/close-pull@v2
+        with:
+          pull-request-number:  ${{ steps.create-pr.outputs.pull-request-number }}
+          comment: Auto-closing pull request after testing is successful
+          delete-branch: true
